#!/bin/bash

# >> TERMINAL RADIO PLAYER - 1.0 <<

# Programa que roda a sua web radio preferida via terminal
# usa um módulo (ffplay) do ffmpeg que vc precisa ter instalado
# Você tem a liberdade de aprimorar esse código e distribuir se quiser.

# Author: Jan Cordeiro
# Versão 1.0

clear

echo -e "\e[36;45;1m  +-------------------------------+  \e[0m"
echo -e "\e[36;45;1m  |  >> TERMINAL RADIO PLAYER <<  |  \e[0m"
echo -e "\e[36;45;1m  |  >>           Version 1.0 <<  |  \e[0m"
echo -e "\e[36;45;1m  +-------------------------------+  \e[0m"
echo ""

# Lê a opção selecionada pelo usuário
PS3=$'\n\e[37;45;1m Selecione uma Opção:\e[0m '
select opcao in "Metal Devastations Radio" "Crucial Velocity Radio" "Alternative Rock X-Radio" "Sair"
do
  # Executa o arquivo .sh correspondente à opção selecionada
  case $opcao in
    "Metal Devastations Radio")
      echo ""
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      echo -e "\e[35;40;1m|# Você está ouvindo:\e[0m\e[32;40;5m Metal Devastations Radio \e[0m"
      echo -e "\e[35;1m|-----------------------------------------------------+\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C para voltar a lista\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C 2x para fechar\e[0m"
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      ffplay -nodisp "http://c13.radioboss.fm:8099/autodj" &> /dev/null
      ;;
    "Crucial Velocity Radio")
      echo ""
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      echo -e "\e[35;40;1m|# Você está ouvindo:\e[0m\e[32;40;5m Crucial Velocity Radio \e[0m"
      echo -e "\e[35;1m|-----------------------------------------------------+\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C para voltar a lista\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C 2x para fechar\e[0m"
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      ffplay -nodisp "http://ais-edge23-dal02.cdnstream.com/1369_128" &> /dev/null
      ;;
    "Alternative Rock X-Radio")
      echo ""
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      echo -e "\e[35;40;1m|# Você está ouvindo:\e[0m\e[32;40;5m Alternative Rock X-Radio \e[0m"
      echo -e "\e[35;1m|-----------------------------------------------------+\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C para voltar a lista\e[0m"
      echo -e "\e[35;1m|# Pressione CTRL+C 2x para fechar\e[0m"
      echo -e "\e[35;1m+-----------------------------------------------------+\e[0m"
      ffplay -nodisp "http://ruby.torontocast.com:3340/stream" &> /dev/null
      ;;
    "Sair")
      # Sair do loop e abrir o arquivo .sh
      ./terminal-radio-player-home
      ;;
  esac
./terminal-radio-rock-metal
done
