#!/bin/bash

# >> TERMINAL RADIO PLAYER - 1.0 <<

# Programa que roda a sua web radio preferida via terminal
# usa um módulo (ffplay) do ffmpeg que vc precisa ter instalado
# script baseado em uma versão do Slackjeff a fins de estudo
# Você tem a liberdade de aprimorar esse código e distribuir se quiser.

# Author: Jan Cordeiro <JanLinux>
# Versão 1.0

clear

# Verifica se o ffmpeg está instalado
if command -v ffmpeg > /dev/null 2>&1
then
  # ffmpeg está instalado
  ./terminal-radio-player-home
else
  # ffmpeg não está instalado
  echo "ffmpeg não está instalado!"
  echo "Você pode instalar do seu repositório"
  echo "Com o comando sudo apt install ffmpeg, por exemplo."
  exit 1
fi

